version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - qdrant
    ports:
      - "3000:3000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    volumes:
      - ./backend:/app
      - ./docs-pdf:/app/docs-pdf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia

  frontend:
    build: ./frontend
    ports:
      - "7860:7860"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  qdrant_data:
